version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devopshub-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!"
    ports:
      - "1435:1433"

  backend:
    build: ./backend
    container_name: devopshub-api
    ports:
      - "5002:5001"
    depends_on:
      - sqlserver
    environment:
      PORT: 5001
      DB_SERVER: sqlserver
      DB_USER: sa
      DB_PASSWORD: StrongPass123!
      DB_NAME: devopshub

  frontend:
    build: ./frontend
    container_name: devopshub-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend